app = "pbo-site"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  DATABASE_PATH = "/data/pbo.db"
  GOOGLE_APPLICATION_CREDENTIALS = "/data/google-credentials/pbo-site-2c91419be737.json"
  UPLOADS_DIR = "/data/uploads"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "20s"
    interval = "15s"
    method = "GET"
    path = "/api/health"
    timeout = "5s"

    [http_service.checks.headers]
      X-Forwarded-Proto = "https"

[mounts]
  source = "pbo_data"
  destination = "/data"

[[vm]]
  memory = "2gb"
  cpu_kind = "performance"
  cpus = 1
