"use client";

import Link from "next/link";
import { useState, type ReactNode } from "react";
import type { ExperimentalAppearance, ExperimentalMatch } from "./experimental-stats-client";
import { CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

type InsightAppearance = ExperimentalAppearance & { match: ExperimentalMatch; coachId: number; coachName: string; teamName: string; won: boolean };
type RecordRow = { wins: number; losses: number; games: number };
const format = (value: number, digits = 0) => value.toLocaleString(undefined, { maximumFractionDigits: digits, minimumFractionDigits: digits });
const damage = (appearance: ExperimentalAppearance) => (appearance.damageDealt ?? 0) + (appearance.damageDealtIndirect ?? 0);
const matchTurns = (match: ExperimentalMatch) => Math.max(0, ...match.turnSnapshots.map((snapshot) => snapshot.turn), ...match.keyEvents.map((event) => event.turn));
const winnerSide = (match: ExperimentalMatch) => match.winnerId === match.coach1.seasonCoachId ? "coach1" : match.winnerId === match.coach2.seasonCoachId ? "coach2" : null;
const playerSide = (match: ExperimentalMatch, player?: "p1" | "p2") => !player || match.p1IsCoach1 === null ? null : (player === "p1") === match.p1IsCoach1 ? "coach1" : "coach2";
const firstFaint = (match: ExperimentalMatch) => match.keyEvents.filter((event) => event.type === "faint").sort((a, b) => a.turn - b.turn)[0];
const teamNameForAppearance = (appearance: InsightAppearance) => appearance.seasonCoachId === appearance.match.coach1.seasonCoachId ? appearance.match.coach1.teamName : appearance.match.coach2.teamName;
const percent = (value: number, total: number) => total ? `${format(value / total * 100, 1)}%` : "—";

function downloadCsv(filename: string, rows: Array<Array<string | number>>) {
  const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n");
  const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
  const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url);
}

function combinations(names: string[], size: 2 | 3) {
  const sorted = [...new Set(names)].sort((a, b) => a.localeCompare(b)); const output: string[][] = [];
  const visit = (start: number, selected: string[]) => { if (selected.length === size) { output.push(selected); return; } for (let index = start; index < sorted.length; index += 1) visit(index + 1, [...selected, sorted[index]]); };
  visit(0, []); return output;
}

export function ExperimentalInsights({ matches, appearances }: { matches: ExperimentalMatch[]; appearances: InsightAppearance[] }) {
  const [compareA, setCompareA] = useState<number | null>(matches[0]?.id ?? null);
  const [compareB, setCompareB] = useState<number | null>(matches[1]?.id ?? matches[0]?.id ?? null);
  const [saved, setSaved] = useState(false);
  const activeCompareA = compareA && matches.some((match) => match.id === compareA) ? compareA : matches[0]?.id ?? null;
  const activeCompareB = compareB && matches.some((match) => match.id === compareB) ? compareB : matches[1]?.id ?? matches[0]?.id ?? null;

  const firstFaintRows = matches.flatMap((match) => { const faint = firstFaint(match); const side = playerSide(match, faint?.player); const winner = winnerSide(match); return faint && side && winner ? [{ match, faint, comeback: side === winner }] : []; });
  const firstFaintWins = firstFaintRows.filter((row) => !row.comeback).length; const comebackWins = firstFaintRows.filter((row) => row.comeback).length;
  const conversion = new Map<string, { name: string; teamName: string; kills: number; deaths: number; appearances: number }>();
  appearances.forEach((appearance) => { const key = `${appearance.pokemonId}:${appearance.seasonCoachId}`; const row = conversion.get(key) ?? { name: appearance.pokemonName, teamName: teamNameForAppearance(appearance), kills: 0, deaths: 0, appearances: 0 }; row.kills += appearance.kills; row.deaths += appearance.deaths; row.appearances += 1; conversion.set(key, row); });
  const conversionRows = [...conversion.values()].filter((row) => row.kills + row.deaths > 0).map((row) => ({ ...row, rate: row.kills / (row.kills + row.deaths) * 100 })).sort((a, b) => b.rate - a.rate || b.kills - a.kills).slice(0, 6);

  const teamDamage = new Map<string, number>();
  matches.forEach((match) => match.pokemon.forEach((appearance) => teamDamage.set(`${match.id}:${appearance.seasonCoachId}`, (teamDamage.get(`${match.id}:${appearance.seasonCoachId}`) ?? 0) + damage(appearance))));
  const shareRows = new Map<string, { name: string; teamName: string; total: number; covered: number }>();
  appearances.filter((appearance) => appearance.damageDealt !== null).forEach((appearance) => { const total = teamDamage.get(`${appearance.match.id}:${appearance.seasonCoachId}`) ?? 0; if (!total) return; const key = `${appearance.pokemonId}:${appearance.seasonCoachId}`; const row = shareRows.get(key) ?? { name: appearance.pokemonName, teamName: teamNameForAppearance(appearance), total: 0, covered: 0 }; row.total += damage(appearance) / total * 100; row.covered += 1; shareRows.set(key, row); });
  const topShare = [...shareRows.values()].map((row) => ({ ...row, average: row.total / row.covered })).sort((a, b) => b.average - a.average).slice(0, 6);

  const koMoves = new Map<string, number>();
  matches.forEach((match) => match.keyEvents.filter((event) => event.type === "faint" && event.move).forEach((event) => { const move = event.move?.trim(); if (move) koMoves.set(move, (koMoves.get(move) ?? 0) + 1); }));
  const topKoMoves = [...koMoves].sort((a, b) => b[1] - a[1]).slice(0, 8);

  const matchupMap = new Map<string, RecordRow & { left: string; right: string }>();
  matches.forEach((match) => { const left = match.pokemon.filter((appearance) => appearance.seasonCoachId === match.coach1.seasonCoachId); const right = match.pokemon.filter((appearance) => appearance.seasonCoachId === match.coach2.seasonCoachId); left.forEach((a) => right.forEach((b) => { const key = `${a.pokemonName}|${b.pokemonName}`; const row = matchupMap.get(key) ?? { left: a.pokemonName, right: b.pokemonName, wins: 0, losses: 0, games: 0 }; row.games += 1; if (match.winnerId === match.coach1.seasonCoachId) row.wins += 1; else row.losses += 1; matchupMap.set(key, row); })); });
  const matchups = [...matchupMap.values()].filter((row) => row.games >= 2).sort((a, b) => b.games - a.games || b.wins - a.wins).slice(0, 8);

  const coachRows = [...new Map(appearances.map((appearance) => [appearance.coachId, appearance.coachName])).entries()].map(([coachId, coachName]) => { const rows = appearances.filter((appearance) => appearance.coachId === coachId); const pokemon = new Map<string, number>(); rows.forEach((appearance) => pokemon.set(appearance.pokemonName, (pokemon.get(appearance.pokemonName) ?? 0) + 1)); const favorite = [...pokemon].sort((a, b) => b[1] - a[1])[0]; const damageRows = rows.filter((appearance) => appearance.damageDealt !== null); return { coachId, coachName, appearances: rows.length, wins: rows.filter((row) => row.won).length, damage: damageRows.reduce((sum, row) => sum + damage(row), 0), damageApps: damageRows.length, favorite: favorite?.[0] ?? "—" }; }).sort((a, b) => b.wins - a.wins || b.appearances - a.appearances).slice(0, 10);

  const itemRows = new Map<string, { item: string; wins: number; appearances: number; matches: ExperimentalMatch[] }>();
  appearances.flatMap((appearance) => [...new Set(appearance.revealedItems.map((item) => item.item).filter(Boolean))].map((item) => ({ appearance, item }))).forEach(({ appearance, item }) => { const row = itemRows.get(item) ?? { item, wins: 0, appearances: 0, matches: [] }; row.appearances += 1; if (appearance.won) row.wins += 1; if (!row.matches.some((match) => match.id === appearance.match.id)) row.matches.push(appearance.match); itemRows.set(item, row); });
  const topItems = [...itemRows.values()].sort((a, b) => b.appearances - a.appearances).slice(0, 8);

  const paceRows = matches.map((match) => ({ match, turns: matchTurns(match) })).filter((row) => row.turns > 0); const averageTurns = paceRows.length ? paceRows.reduce((sum, row) => sum + row.turns, 0) / paceRows.length : null; const averageFirstFaint = firstFaintRows.length ? firstFaintRows.reduce((sum, row) => sum + row.faint.turn, 0) / firstFaintRows.length : null;
  const momentumMatch = matches.find((match) => match.turnSnapshots.length > 0) ?? null; const momentumData = momentumMatch?.turnSnapshots.map((snapshot) => ({ turn: snapshot.turn, [momentumMatch.coach1.teamName]: Math.round(snapshot.p1TotalHp), [momentumMatch.coach2.teamName]: Math.round(snapshot.p2TotalHp) })) ?? [];

  const coreMap = new Map<string, RecordRow & { core: string }>();
  matches.forEach((match) => [match.coach1.seasonCoachId, match.coach2.seasonCoachId].forEach((seasonCoachId) => combinations(match.pokemon.filter((appearance) => appearance.seasonCoachId === seasonCoachId).map((appearance) => appearance.pokemonName), 3).forEach((core) => { const key = core.join("|"); const row = coreMap.get(key) ?? { core: core.join(" + "), wins: 0, losses: 0, games: 0 }; row.games += 1; if (match.winnerId === seasonCoachId) row.wins += 1; else row.losses += 1; coreMap.set(key, row); })));
  const topCores = [...coreMap.values()].filter((row) => row.games >= 2).sort((a, b) => b.wins - a.wins || b.games - a.games).slice(0, 6);
  const stageRows = coachRows.map((coach) => { const rows = appearances.filter((appearance) => appearance.coachId === coach.coachId); const regular = rows.filter((appearance) => appearance.match.week <= 100); const playoffs = rows.filter((appearance) => appearance.match.week > 100); return { ...coach, regular, playoffs, regularDamage: regular.filter((row) => row.damageDealt !== null), playoffDamage: playoffs.filter((row) => row.damageDealt !== null) }; }).filter((row) => row.regular.length && row.playoffs.length).slice(0, 8);

  const selectedA = matches.find((match) => match.id === activeCompareA) ?? matches[0]; const selectedB = matches.find((match) => match.id === activeCompareB) ?? matches[1] ?? matches[0];
  const coverage = { timelines: matches.filter((match) => match.turnSnapshots.length > 0).length, faintLogs: matches.filter((match) => match.keyEvents.length > 0).length, moves: appearances.filter((appearance) => appearance.moveDataRecorded).length, items: appearances.filter((appearance) => appearance.itemDataRecorded).length };
  const saveReport = () => { window.localStorage.setItem("pbo-experimental-stats-report", JSON.stringify({ savedAt: new Date().toISOString(), matches: matches.length, appearances: appearances.length })); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  const exportCoachRows = () => downloadCsv("pbo-coach-tendencies.csv", [["Coach", "Appearances", "Wins", "Win rate", "Favorite Pokemon", "Recorded damage"], ...coachRows.map((row) => [row.coachName, row.appearances, row.wins, percent(row.wins, row.appearances), row.favorite, row.damageApps ? format(row.damage / row.damageApps, 1) : ""])]);

  return <section className="space-y-4">
    <div className="poke-card border-violet-400/25 bg-violet-500/[0.04] p-5 md:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-pixel text-sm text-white">Advanced replay lab</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-[var(--foreground-muted)]">Momentum, matchups, roles, pace, items, cores, and playoff changes from the active replay filters.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={saveReport} className="btn-retro-secondary px-3 py-2 text-[9px]">{saved ? "Saved" : "Save report"}</button><button type="button" onClick={exportCoachRows} className="btn-retro-secondary px-3 py-2 text-[9px]">Export tendencies</button></div></div><div className="mt-4 flex flex-wrap gap-2 text-[9px] font-bold"><ConfidenceBadge tone="full" text={`${coverage.timelines}/${matches.length} timelines`} /><ConfidenceBadge tone="partial" text={`${coverage.faintLogs}/${matches.length} faint logs`} /><ConfidenceBadge tone="full" text={`${coverage.moves}/${appearances.length} move records`} /></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><InsightCard label="First-faint advantage" value={percent(firstFaintWins, firstFaintRows.length)} detail={firstFaintRows.length ? `${firstFaintWins} of ${firstFaintRows.length} mapped matches` : "No mapped faint order yet"} /><InsightCard label="Comeback wins" value={format(comebackWins)} detail="Winner was first to lose a Pokémon" /><InsightCard label="Average match pace" value={averageTurns === null ? "—" : `${format(averageTurns, 1)} turns`} detail={averageFirstFaint === null ? "First faint timing unavailable" : `First faint at turn ${format(averageFirstFaint, 1)}`} /><InsightCard label="Item coverage" value={percent(coverage.items, appearances.length)} detail="Appearances with saved item data" /></div></div>
    <div className="grid gap-4 xl:grid-cols-2"><div className="poke-card p-5 md:p-6"><h3 className="font-pixel text-xs text-white">Battle momentum</h3><p className="mt-1 text-[10px] text-[var(--foreground-muted)]">Team HP is a momentum proxy. It shows who held the lead, not every tactical decision.</p>{momentumData.length ? <div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={momentumData}><CartesianGrid strokeDasharray="3 3" stroke="var(--background-tertiary)" /><XAxis dataKey="turn" stroke="var(--foreground-muted)" tick={{ fontSize: 9 }} /><YAxis stroke="var(--foreground-muted)" tick={{ fontSize: 9 }} /><Tooltip contentStyle={{ background: "var(--background-secondary)", border: "1px solid var(--border)" }} /><Legend wrapperStyle={{ fontSize: 10 }} /><Line type="monotone" dataKey={momentumMatch?.coach1.teamName} stroke="#22d3ee" dot={false} /><Line type="monotone" dataKey={momentumMatch?.coach2.teamName} stroke="#e879f9" dot={false} /></LineChart></ResponsiveContainer></div> : <EmptyMessage text="No saved team HP timeline is available in this scope." />}</div><div className="poke-card p-5 md:p-6"><h3 className="font-pixel text-xs text-white">Battle pace records</h3><div className="mt-4 grid grid-cols-2 gap-3"><InsightCard label="Fastest replay" value={paceRows.length ? `${Math.min(...paceRows.map((row) => row.turns))} turns` : "—"} detail="Shortest saved timeline" /><InsightCard label="Longest replay" value={paceRows.length ? `${Math.max(...paceRows.map((row) => row.turns))} turns` : "—"} detail="Longest saved timeline" /></div><div className="mt-4 text-xs text-[var(--foreground-muted)]">{paceRows.length} replay timelines support pace measurements.</div></div></div>
    <div><DataTable title="Pokémon matchup matrix" description="Cross-team Pokémon records from repeated appearances." headers={["Matchup", "Record", "Games", "Win rate"]} rows={matchups.map((row) => [`${row.left} vs ${row.right}`, `${row.wins}-${row.losses}`, row.games, percent(row.wins, row.games)])} empty="Not enough repeated matchup data." /></div>
    <div className="grid gap-4 xl:grid-cols-2"><DataTable title="KO conversion" description="Recorded kills divided by kills plus deaths, credited to each team." headers={["Pokémon", "Team", "KOs", "Deaths", "Conversion"]} rows={conversionRows.map((row) => [row.name, row.teamName, row.kills, row.deaths, `${format(row.rate, 1)}%`])} empty="No recorded KOs or deaths." /><DataTable title="Team damage share" description="Average share of recorded team damage by Pokémon, credited to each team." headers={["Pokémon", "Team", "Average share", "Covered apps"]} rows={topShare.map((row) => [row.name, row.teamName, `${format(row.average, 1)}%`, row.covered])} empty="No damage coverage." /></div>
    <div className="grid gap-4 xl:grid-cols-2"><DataTable title="Coach tendencies" description="Favorite Pokémon, wins, and recorded damage by coach." headers={["Coach", "Record", "Favorite", "Damage / app"]} rows={coachRows.map((row) => [row.coachName, `${row.wins}-${row.appearances - row.wins}`, row.favorite, row.damageApps ? format(row.damage / row.damageApps, 1) : "—"])} empty="No coach tendency data." /><DataTable title="Item impact" description="Win rates associated with revealed items; open a game link to review the source match." headers={["Item", "Wins", "Apps", "Win rate", "Games"]} rows={topItems.map((row) => [row.item, row.wins, row.appearances, percent(row.wins, row.appearances), <ItemMatchLinks key={row.item} matches={row.matches} />])} empty="No saved item reveals." /></div>
    <div className="grid gap-4 xl:grid-cols-2"><DataTable title="Three-Pokémon cores" description="Repeated three-Pokémon combinations with recorded win-loss results." headers={["Core", "Record", "Games", "Win rate"]} rows={topCores.map((row) => [row.core, `${row.wins}-${row.losses}`, row.games, percent(row.wins, row.games)])} empty="Not enough repeated cores." /><DataTable title="Move-to-KO signals" description="Moves attached to saved faint events. Use this as a lead, not a complete damage model." headers={["Move", "Recorded KOs"]} rows={topKoMoves.map(([move, count]) => [move, count])} empty="No faint events include a move name." /></div>
    <div className="poke-card p-5 md:p-6"><h3 className="font-pixel text-xs text-white">Regular season versus playoffs</h3><p className="mt-1 text-[10px] text-[var(--foreground-muted)]">Compare the same coach only when both stages are present in the active scope.</p>{stageRows.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-xs"><thead className="text-[9px] uppercase text-[var(--foreground-muted)]"><tr><th className="p-2 text-left">Coach</th><th>Regular record</th><th>Playoff record</th><th>Regular damage</th><th>Playoff damage</th><th>Shift</th></tr></thead><tbody>{stageRows.map((row) => { const regularDamage = row.regularDamage.length ? row.regularDamage.reduce((sum, appearance) => sum + damage(appearance), 0) / row.regularDamage.length : null; const playoffDamage = row.playoffDamage.length ? row.playoffDamage.reduce((sum, appearance) => sum + damage(appearance), 0) / row.playoffDamage.length : null; const shift = regularDamage !== null && playoffDamage !== null ? playoffDamage - regularDamage : null; return <tr key={row.coachId} className="border-t border-[var(--border)] text-center"><td className="p-2 text-left font-bold text-white">{row.coachName}</td><td>{row.regular.filter((appearance) => appearance.won).length}-{row.regular.filter((appearance) => !appearance.won).length}</td><td>{row.playoffs.filter((appearance) => appearance.won).length}-{row.playoffs.filter((appearance) => !appearance.won).length}</td><td>{regularDamage === null ? "—" : format(regularDamage, 1)}</td><td>{playoffDamage === null ? "—" : format(playoffDamage, 1)}</td><td className={shift !== null && shift >= 0 ? "text-emerald-300" : "text-red-300"}>{shift === null ? "—" : `${shift >= 0 ? "+" : ""}${format(shift, 1)}`}</td></tr>; })}</tbody></table></div> : <EmptyMessage text="Choose a scope containing both regular-season and playoff matches." />}</div>
    <div className="poke-card p-5 md:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="font-pixel text-xs text-white">Replay comparison</h3><p className="mt-1 text-[10px] text-[var(--foreground-muted)]">Compare two saved battles side by side.</p></div><div className="flex flex-wrap gap-2"><MatchSelect matches={matches} value={activeCompareA} onChange={setCompareA} /><MatchSelect matches={matches} value={activeCompareB} onChange={setCompareB} /></div></div>{selectedA && selectedB ? <div className="mt-5 grid gap-3 md:grid-cols-2"><ComparisonCard match={selectedA} /><ComparisonCard match={selectedB} /></div> : <EmptyMessage text="At least one replay is needed for comparison." />}</div>
  </section>;
}

function MatchSelect({ matches, value, onChange }: { matches: ExperimentalMatch[]; value: number | null; onChange: (value: number) => void }) { return <select value={value ?? ""} onChange={(event) => onChange(Number(event.target.value))} className="max-w-full rounded-lg border-2 border-[var(--background-tertiary)] bg-[var(--background)] px-2 py-2 text-[10px] font-bold"><option value="">Choose replay</option>{matches.map((match) => <option key={match.id} value={match.id}>{match.coach1.teamName} vs {match.coach2.teamName} · W{match.week}</option>)}</select>; }
function ComparisonCard({ match }: { match: ExperimentalMatch }) { const faint = firstFaint(match); const totalDamage = match.pokemon.reduce((sum, appearance) => sum + damage(appearance), 0); const winner = match.winnerId === match.coach1.seasonCoachId ? match.coach1.teamName : match.coach2.teamName; return <div className="rounded-xl border border-[var(--border)] bg-[var(--background)] p-4"><div className="text-xs font-bold text-white">{match.coach1.teamName} vs {match.coach2.teamName}</div><div className="mt-1 text-[10px] text-[var(--foreground-muted)]">{match.seasonName} · {match.divisionName} · Week {match.week}</div><div className="mt-4 grid grid-cols-2 gap-2 text-center text-xs"><MetricCell label="Winner" value={winner} /><MetricCell label="Turns" value={matchTurns(match) ? format(matchTurns(match)) : "—"} /><MetricCell label="First faint" value={faint ? `T${faint.turn}` : "—"} /><MetricCell label="Damage" value={totalDamage ? `${format(totalDamage, 1)}%` : "—"} /></div></div>; }
function MetricCell({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-[var(--border)] p-2"><div className="text-[8px] uppercase text-[var(--foreground-muted)]">{label}</div><div className="mt-1 break-words font-mono text-[11px] font-black text-white">{value}</div></div>; }
function ConfidenceBadge({ tone, text }: { tone: "full" | "partial" | "limited"; text: string }) { const color = tone === "full" ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : tone === "partial" ? "border-amber-400/30 bg-amber-400/10 text-amber-200" : "border-slate-500/30 bg-slate-500/10 text-slate-300"; return <span className={`rounded-full border px-2 py-1 ${color}`}>{text}</span>; }
function InsightCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-xl border border-slate-700/70 bg-slate-950/60 p-3 text-center"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-2 break-words font-mono text-xl font-black text-white">{value}</div><div className="mt-1 text-[10px] leading-4 text-[var(--foreground-subtle)]">{detail}</div></div>; }
function EmptyMessage({ text }: { text: string }) { return <p className="mt-4 text-xs text-[var(--foreground-muted)]">{text}</p>; }
function ItemMatchLinks({ matches }: { matches: ExperimentalMatch[] }) { return <div className="max-h-24 max-w-[220px] overflow-y-auto"><div className="flex flex-wrap justify-center gap-1"><span className="sr-only">Games featuring this item</span>{matches.map((match) => <Link key={match.id} href={match.isDemo ? "/experimental-stats?demo=1" : `/matches/${match.id}`} aria-label={`${match.seasonName} Week ${match.week}: ${match.coach1.teamName} versus ${match.coach2.teamName}`} title={`${match.coach1.teamName} vs ${match.coach2.teamName}`} className="rounded border border-[var(--border)] px-1.5 py-0.5 text-[9px] font-bold text-[var(--primary)] hover:border-[var(--primary)] hover:text-white">{match.seasonName} · W{match.week}</Link>)}</div></div>; }
function DataTable({ title, description, headers, rows, empty }: { title: string; description: string; headers: string[]; rows: Array<Array<ReactNode>>; empty: string }) { return <div className="poke-card p-5 md:p-6"><h3 className="font-pixel text-xs text-white">{title}</h3><p className="mt-1 text-[10px] leading-4 text-[var(--foreground-muted)]">{description}</p>{rows.length ? <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[430px] text-xs"><thead className="text-[9px] uppercase text-[var(--foreground-muted)]"><tr>{headers.map((header, index) => <th key={header} className={`p-2 ${index === 0 ? "text-left" : "text-center"}`}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={`${title}-${index}`} className="border-t border-[var(--border)]">{row.map((cell, cellIndex) => <td key={`${index}-${cellIndex}`} className={`p-2 ${cellIndex === 0 ? "font-bold text-white" : "text-center font-mono"}`}>{cell}</td>)}</tr>)}</tbody></table></div> : <EmptyMessage text={empty} />}</div>; }
